#!/bin/bash
# Quick script to set up FREE Redis Labs and update your production environment

echo "🎓 FREE Redis Setup for Students - Redis Labs"
echo "=============================================="
echo ""
echo "📝 Step-by-step instructions:"
echo ""
echo "1️⃣  Sign up for FREE Redis Labs account:"
echo "   👉 https://redis.com/try-free/"
echo "   - Use your student email"
echo "   - 100% FREE, no credit card required"
echo "   - 30MB storage (more than enough)"
echo ""
echo "2️⃣  Create a new database:"
echo "   - Click 'Create database'"
echo "   - Name: ai-cruel-redis"
echo "   - Cloud: AWS"
echo "   - Region: Choose closest to you (e.g., us-east-1)"
echo "   - Click 'Activate database'"
echo ""
echo "3️⃣  Get your connection string:"
echo "   - Click on your database"
echo "   - Look for 'Public endpoint'"
echo "   - It will look like: redis-12345.c123.us-east-1-1.ec2.cloud.redislabs.com:12345"
echo "   - Click on 'Copy' to get the password"
echo ""
echo "4️⃣  Your REDIS_URL format:"
echo "   redis://default:<YOUR_PASSWORD>@<ENDPOINT>:<PORT>"
echo "   Example:"
echo "   redis://default:ABC123XYZ@redis-12345.c123.us-east-1-1.ec2.cloud.redislabs.com:12345"
echo ""
echo "5️⃣  Update on Digital Ocean:"
echo "   👉 https://cloud.digitalocean.com/apps"
echo "   - Click on your 'ai-cruel-backend' app"
echo "   - Go to 'Settings' → 'App-Level Environment Variables'"
echo "   - Find REDIS_URL and click 'Edit'"
echo "   - Paste your new Redis Labs connection string"
echo "   - Click 'Save' (this will trigger auto-redeploy)"
echo ""
echo "6️⃣  Wait for redeploy (2-3 minutes)"
echo "   - Watch the deployment logs in DO dashboard"
echo "   - Once it says 'Deployment successful', you're done!"
echo ""
echo "7️⃣  Verify it's working:"
echo "   curl http://198.211.106.97:8000/debug/celery"
echo "   You should see 'celery_configured: true'"
echo ""
echo "✅ After this, your email reminders will work automatically!"
echo "   - Celery Beat will check every 5 minutes"
echo "   - Emails will be sent 1 hour and 1 day before deadlines"
echo ""
echo "💡 Alternative FREE option (if Redis Labs doesn't work):"
echo "   Use Railway.app FREE Redis:"
echo "   1. Go to https://railway.app/"
echo "   2. Sign up with GitHub (FREE $5 credit, no card needed)"
echo "   3. Click 'New Project' → 'Deploy Redis'"
echo "   4. Get the REDIS_URL from the Redis service settings"
echo "   5. Update in Digital Ocean as described above"
echo ""
echo "Need help? The setup takes less than 10 minutes!"
echo "=============================================="
